pygments: true
download:
    version: 0.5.1 alpha
    date: "August 25, 2011"
    size: 15kb gzipped
    blurb: Initial alpha release of batman.js. Please see the blog post or release notes for more information.
examples:
    - title: Hello World
      key: hello world
    - title: Alfred - Batman's Todos
      key: alfred
